# PCA

In [63]:
import numpy as np
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline

## Q.1- Import MNIST dataset from sklearn. Save data and targets in variables X and Y respectively.

In [64]:
from sklearn.datasets import load_digits
data , target = load_digits(n_class = 10 , return_X_y = True)

In [65]:
data.shape

(1797, 64)

In [66]:
target.shape

(1797,)

In [67]:
x = pd.DataFrame(data)
y = pd.DataFrame(target)

In [68]:
x.describe()

0            1            2            3            4   \
count  1797.0  1797.000000  1797.000000  1797.000000  1797.000000   
mean      0.0     0.303840     5.204786    11.835838    11.848080   
std       0.0     0.907192     4.754826     4.248842     4.287388   
min       0.0     0.000000     0.000000     0.000000     0.000000   
25%       0.0     0.000000     1.000000    10.000000    10.000000   
50%       0.0     0.000000     4.000000    13.000000    13.000000   
75%       0.0     0.000000     9.000000    15.000000    15.000000   
max       0.0     8.000000    16.000000    16.000000    16.000000   

                5            6            7            8            9   \
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000   
mean      5.781859     1.362270     0.129661     0.005565     1.993879   
std       5.666418     3.325775     1.037383     0.094222     3.196160   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       4.000000     0.000000     0.000000     0.000000     0.000000   
75%      11.000000     0.000000     0.000000     0.000000     3.000000   
max      16.000000    16.000000    15.000000     2.000000    16.000000   

          ...                54           55           56           57  \
count     ...       1797.000000  1797.000000  1797.000000  1797.000000   
mean      ...          3.725097     0.206455     0.000556     0.279354   
std       ...          4.919406     0.984401     0.023590     0.934302   
min       ...          0.000000     0.000000     0.000000     0.000000   
25%       ...          0.000000     0.000000     0.000000     0.000000   
50%       ...          1.000000     0.000000     0.000000     0.000000   
75%       ...          7.000000     0.000000     0.000000     0.000000   
max       ...         16.000000    13.000000     1.000000     9.000000   

                58           59           60           61           62  \
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000   
mean      5.557596    12.089037    11.809126     6.764051     2.067891   
std       5.103019     4.374694     4.933947     5.900623     4.090548   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       1.000000    11.000000    10.000000     0.000000     0.000000   
50%       4.000000    13.000000    14.000000     6.000000     0.000000   
75%      10.000000    16.000000    16.000000    12.000000     2.000000   
max      16.000000    16.000000    16.000000    16.000000    16.000000   

                63  
count  1797.000000  
mean      0.364496  
std       1.860122  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max      16.000000  

[8 rows x 64 columns]

In [69]:
y.describe()

0
count  1797.000000
mean      4.490818
std       2.865304
min       0.000000
25%       2.000000
50%       4.000000
75%       7.000000
max       9.000000

## Q.2- Perform feature scaling. 

In [70]:
from sklearn.preprocessing import StandardScaler
x = StandardScaler().fit_transform(x)

## Q.3- Split data into training and testing sets.

In [71]:
from sklearn.model_selection import train_test_split
train_x , test_x , train_y , test_y = train_test_split(x , y , test_size = 0.3 , random_state =0)

## Q.4- Perform PCA. Take any value for components.

In [72]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 10)
principalComponents = pca.fit_transform(x)
pdf = pd.DataFrame(principalComponents)
pdf.head()

0         1         2         3         4         5         6  \
0  1.914492 -0.954296 -3.945310  2.028122 -0.256100  0.530815 -1.408396   
1  0.588899  0.924593  3.924726 -1.779372 -0.993072 -0.674739  1.879355   
2  1.301216 -0.317820  3.021683 -2.042224 -2.107316  0.930619 -1.312607   
3 -3.020375 -0.868454 -0.800965 -2.187707 -0.546046  0.729411  0.966176   
4  4.529672 -1.092949  0.974302 -1.420448 -1.699732  1.432354  1.083536   

          7         8         9  
0  1.488156  0.119805 -0.811608  
1  0.552578  1.093460  0.109271  
2  1.167430  0.790641 -1.238381  
3 -1.382660  0.256878  0.829187  
4 -0.955967 -1.677248  1.279029

## Q.5- Perform classification (logistic regression).

In [73]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(train_x , train_y)
pred_y = model.predict(test_x)

C:\Users\Public\Anaconda2\envs\py36\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## Q.6- Print the following: 
### a. Accuracy score

In [74]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report
print(accuracy_score(test_y ,pred_y))

0.9537037037037037


### b. Confusion Matrix

In [75]:
print(confusion_matrix(test_y ,pred_y))

[[45  0  0  0  0  0  0  0  0  0]
 [ 0 49  0  0  0  0  1  0  2  0]
 [ 0  2 50  1  0  0  0  0  0  0]
 [ 0  0  1 52  0  0  0  0  1  0]
 [ 0  0  0  0 47  0  0  1  0  0]
 [ 0  1  0  0  0 55  1  0  0  0]
 [ 0  1  0  0  0  0 59  0  0  0]
 [ 0  0  0  2  0  0  0 51  0  0]
 [ 0  4  1  1  0  0  1  0 53  1]
 [ 0  0  0  0  0  2  0  1  0 54]]


### c. Classification Report

In [76]:
print(classification_report(test_y ,pred_y))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        45
          1       0.86      0.94      0.90        52
          2       0.96      0.94      0.95        53
          3       0.93      0.96      0.95        54
          4       1.00      0.98      0.99        48
          5       0.96      0.96      0.96        57
          6       0.95      0.98      0.97        60
          7       0.96      0.96      0.96        53
          8       0.95      0.87      0.91        61
          9       0.98      0.95      0.96        57

avg / total       0.95      0.95      0.95       540

